# Site settings
title: dip scd
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://dip-scd.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]